### ISSUE TITLE
How to Convert UUID to MAC 

### ISSUE THREAD

**Issue by mohitjadav86** [lengockhoa90/FlutterBlufi#7]
- I want to show MAC Address within the listing but in ios, we are getting UUID it is possible to show  MAC Address in IOS also.
- Or any thing else so we can convert UUID to MAC

**Comment by scsonic** [comment]
impossible in ios
or make your own gatt command to pass mac

**Comment by mohitjadav86** [comment]
I have resolved this issue with the help of getting the required data from the chip side.
